### PR TITLE
auth: login: use next free port

### LINKED ISSUE #80: Feat: Retry other ports if 8000 is occupied for `stackit auth login`
Hello,
`stackit auth login` needs to open a webUI on localhost:8000. If this port is occupied it fails with:
> Error: authorization failed: listen to port :8000: listen tcp :8000: bind: address already in use

 I now had to disable my development resources disrupting my workflow. A retry loop trying different ports would be convenient.
If you want that as a contribution let me know!

### PR DESCRIPTION
**Pull request by gfelbing**
fixes #80.

This PR tries to address the issue of a fixed redirect port by choosing a random free one.

- [x] Use listener on next free port
- [x] While being complete codewise, the oauth config does not work: When using a different port than 8000, the login results in an error: `Invalid redirect http://localhost:40235 did not match one of the registered values`. This needs to be fixed by maintainers first.

Screenshot:

image

### CODE REVIEW

**Comment by joaopalet** [comment]
Hi @gfelbing,

Thanks for the initiative!

We need to adjust the valid redirect URLs in the identity provider client configuration to allow the use of any local port. We are currently looking into it

**Comment by joaopalet** [comment]
Hi @gfelbing,

The valid redirect URIs were adjusted to allow any port, I just tested this and it worked for me 👍

**Review by joaopalet — DISMISSED** [review]

**Comment by gfelbing** [comment]
@joaopalet thanks! I updated the PR to the latest main and re-tested: works :tada:

**Comment by joaopalet** [comment]
Nice :)

The linter is still complaining as the type assertion must be checked (if it's `ok`)

File: internal/pkg/auth/user_login.go [hunk 1]
```diff
@@ -39,6 +37,13 @@ type User struct {
 
 // AuthorizeUser implements the PKCE OAuth2 flow.
 func AuthorizeUser() error {
+	listener, err := net.Listen("tcp", ":0")
+	if err != nil {
+		return fmt.Errorf("bind port for login redirect: %w", err)
+	}
+	port := listener.Addr().(*net.TCPAddr).Port
```
Comment (joaopalet) [inline internal/pkg/auth/user_login.go:44]:
```suggestion
	port, ok := listener.Addr().(*net.TCPAddr).Port
        if !ok {
		return fmt.Errorf("asserting listener address type to TCP address")
	}
```

File: internal/pkg/auth/user_login.go [hunk 2]
```diff
@@ -39,6 +37,16 @@ type User struct {
...
 func AuthorizeUser() error {
+	listener, err := net.Listen("tcp", ":0")
+	if err != nil {
+		return fmt.Errorf("bind port for login redirect: %w", err)
+	}
+	port, ok := listener.Addr().(*net.TCPAddr).Port
+        if !ok {
+		return fmt.Errorf("assert listener address type to TCP address")
+	}
+	redirectURL := fmt.Sprintf("http://localhost:%d", port)
```
Comment (joaopalet) [inline internal/pkg/auth/user_login.go:48]:
```suggestion
	address, ok := listener.Addr().(*net.TCPAddr)
	if !ok {
		return fmt.Errorf("assert listener address type to TCP address")
	}
	redirectURL := fmt.Sprintf("http://localhost:%d", address.Port)
```

Comment (joaopalet) [reply internal/pkg/auth/user_login.go:48]: Sorry, I had overlooked it

**Review by joaopalet — APPROVED** [review]
